# 로컬 윈도우즈에서 DB-Boot-React 실행하기
services:
  mysql-svc:
    image: mariadb:10.11.8
    ports:
    - "3306:3306"
    volumes:
      #- C:/docker-volume/mariadb/conf.d:/etc/mysql/conf.d
      - C:/mydeploy/docker-volume/mariadb/store:/var/lib/mysql
    env_file: C:/mydeploy/docker-volume/mariadb/env/.env

  mywas:
    image: vega2k8s/springbootreactjs:0.5
    ports:
      - "8080:8080"
    depends_on:
      - mysql-svc
    restart: always
    env_file: C:/mydeploy/docker-volume/mariadb/env/.env
    # environment:
      # DB_HOST: 'mysql-svc'
      # DB_PORT: '3306'
      # DB_DATABASE: 'boot_db'
      # DB_USERNAME: 'boot'
      # DB_PASSWORD: 'boot'

  mynginx:
    image: vega2k8s/springbootreactjs:client0.3
    depends_on:
      - mywas
    ports:
      - "80:80"