apiVersion: v1
kind: Service
metadata:
  name: boot-crud-lb
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: boot-crud
    tier: app