apiVersion: v1
kind: Service
metadata:
  name: boot-crud-np
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30090
  selector:
    app: boot-crud
    tier: app