apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-crud
spec:
  selector:
    matchLabels:
      app: boot-crud
      tier: app
  template:
    metadata:
      labels:
        app: boot-crud
        tier: app
    spec:
      containers:
        - name: boot-crud
          image: bmsvega2k/boot-crud:0.1
          ports:
            - containerPort: 8080
          resources:  # 리소스 제한 추가
            requests:
              cpu: "200m"    # 0.2 CPU 코어 (최소 보장)
              memory: "512Mi" # 512MB 메모리 (최소 보장)
            limits:
              cpu: "500m"     # 0.5 CPU 코어 (최대 사용량)
              memory: "1Gi"   # 1GB 메모리 (최대 사용량)            
          env:
            - name: DB_HOST
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  host
            - name: DB_NAME
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName
            - name: DB_USERNAME
              valueFrom :
                secretKeyRef:
                  name: mysql-secrets
                  key :  username
            - name: DB_PASSWORD
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password
