apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  selector:
    matchLabels:
      app: mysql-pod
      tier: db
  template:
    metadata:
      labels:
        app: mysql-pod
        tier: db
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.4.16
          resources:
            requests:
              cpu: "500m"  # 0.5 CPU 코어
              memory: "512Mi"  # 512MB 메모리
            limits:
              cpu: "1000m"  # 1 CPU 코어
              memory: "1Gi"  # 1GB 메모리  
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbName
          ports:
            - containerPort: 3306
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: mysql-pod
    tier: db